name: Publish Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Zip Template
        run: git archive --format=zip --output ./Mtd.Template.zip HEAD:Mtd.Template
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Mtd.Template.zip
          fail_on_unmatched_files: true
          generate_release_notes: true
          draft: false
          prerelease: false
